name: Analyse,Test, build, distribute, release - android

on:
  push:
    branches:
      - master
jobs:
  CI-Upload-APK:
    name: Production build uploading
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

