name: Analyse,Test, build, distribute, release - android

on:
  push:
    branches: [ main ]

jobs:
  CI-Upload-APK:
    name: Production build uploading
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
