name: Analyse,Test, build, distribute, release - android

on:
  push:
    branches:
      - master
jobs:
  CI-Upload-APK:
    name: Production build uploading
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup JDK
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - run: java HelloWorldApp.java

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.3.0'

